### ISSUE TITLE
Version 6.0 incorrect install directory structure

### ISSUE THREAD

**Issue by Neerrm** [gameboy9/FF4FalconDive#11]
Starting in version 6.0, all randomizer files are copied to the steam FF4PR/install folder, which results in the game not being randomized.

Version 5.0.1 and earlier do not have the install/ directory, and the files are copied directly to the main FF4PR steam folder.

Taking the files out of the install/ directory and moving them one level up to match the behavior of previous versions results in the randomizer working as expected.

**Comment by gameboy9** [comment]
This one should be resolved in version 6.0.1.  Please reopen if that's not the case.  Thanks!
