### ISSUE TITLE
Sometimes Cannot Access Underworld

### ISSUE THREAD

**Issue by brickbuckett** [gameboy9/FF4FalconDive#17]
Rando Flags: 05Q9KGX0000375
Seed: 1558334342
Checksum: 7cdc41767d8bd91b

The key items produced did allow me to finish the run if I wanted, but it locked me out completely from the underworld, a 5th character, and other key items that may have been down there.

**Comment by brickbuckett** [comment]
Actually wanted to add, I thought I needed 4 shards to complete, but there was a 5 requirement from this run; so it was unbeatable.

**Comment by gameboy9** [comment]
I'm hoping that version 6.0.3 resolves this issue.  Please reopen if it ultimately does not.  Thanks!
