### ISSUE TITLE
Some of the checks gave nothing

### ISSUE THREAD

**Issue by Odin-Kaze** [gameboy9/FF4FalconDive#2]
In multiple instance on two different seed I received a key Item named "Nothing".

both seed was impossible to complet probably because of that.

![Nothing 1](https://github.com/gameboy9/FF4FalconDive/assets/119276605/b0b0d1b1-17d5-4eca-bc1b-11c3303e4e7a)
![Nothing 2](https://github.com/gameboy9/FF4FalconDive/assets/119276605/f2779d8c-f709-4884-9d38-0ee40465ddd6)

This is the second Seed I tried
Flags: 0VQIK0100000 
Seed: 2013471941

**Comment by gameboy9** [comment]
Awarding "Nothing" is a new feature of 2.0, in substitution of all of the tails. (although the description is incorrect...)

If you get 3 "Nothings", you'll get a key item.  (which could be "Nothing"!)
