### ISSUE TITLE
New Steam update leads to white screen

### ISSUE THREAD

**Issue by drkangel120180** [gameboy9/FF4FalconDive#7]
Steam finally released an update for FF4, and upon trying to use Falcon Dive, I end up with a white screen.  Reverting to vanilla fixes this issue.

**Comment by gameboy9** [comment]
Yeah, the update pretty much destroyed the randomizer.  It's not functional unless you downgrade at this time.

I will need to wait for Memoria to be updated in order for the randomizer to work again.  (https://github.com/Albeoris/Memoria.FFPR/issues/48)

**Comment by drkangel120180** [comment]
I kinda figured that might be the case given what they added into the game.
Fingers crossed it can be updated soon! 

    On Wednesday, January 31, 2024 at 04:55:11 PM EST, Patrick Fifield ***@***.***> wrote:  
 
 


Yeah, the update pretty much destroyed the randomizer. It's not functional unless you downgrade at this time.

I will need to wait for Memoria to be updated in order for the randomizer to work again. (Albeoris/Memoria.FFPR#48)

**Comment by gameboy9** [comment]
I ultimately converted the randomizer from Memoria to Magicite, resolving this issue.
